name: Fuvekonse

services:
  fuvekon-db:
    image: postgres:17
    container_name: fuvekon-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fuvekon
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - fuvekon-db-data:/var/lib/postgresql/data
  fuvekon-cache:
    image: redis:7-alpine
    container_name: fuvekon-cache
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - fuvekon-redis-data:/data
  localstack:
    image: localstack/localstack:latest
    container_name: fuvekon-cloud
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - PERSISTENCE=${PERSISTENCE:-0}
      - SERVICES=s3,sqs,ses,logs,cloudwatch
      - LOCALSTACK_HOST=localhost
      - AWS_DEFAULT_REGION=ap-southeast-1
    volumes:
      - "./.aws/volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.aws/init:/etc/localstack/init/ready.d"
volumes:
  fuvekon-db-data:
  fuvekon-redis-data:
  localstack-data:
